SELECT * FROM CATEGORY;
SELECT * FROM PRODUCTS;
SELECT * FROM STORES;
SELECT * FROM SALES;
SELECT * FROM WARRANTY;


--Query Optimization using index
CREATE INDEX SALES_PRODUCT_ID ON SALES (PRODUCT_ID);

CREATE INDEX SALES_STORE_ID ON SALES (STORE_ID);

CREATE INDEX SALES_SALE_DATE ON SALES (SALE_DATE);



--Questions To Solve





--1. Find the number of stores in each country.
SELECT COUNTRY, COUNT(STORE_ID) AS TOTAL_STORES
FROM STORES
GROUP BY COUNTRY
ORDER BY TOTAL_STORES DESC;




-- 2. Calculate the total number of units sold by each store.

SELECT S.STORE_ID, ST.STORE_NAME, SUM(S.QUANTITY) AS TOTAL_UNITS_SOLDS
FROM SALES AS S
JOIN STORES AS ST ON ST.STORE_ID = S.STORE_ID
GROUP BY S.STORE_ID, ST.STORE_ID
ORDER BY TOTAL_UNITS_SOLDS DESC;



-- 3. Identify how many sales occurred in December 2023.

SELECT COUNT(SALE_ID) AS TOTAL_SALES
FROM SALES
WHERE TO_CHAR(SALE_DATE, 'MM-YYYY') = '12-2023';
	








--3.1 Total quantity sold in December 2023.
SELECT SUM(QUANTITY) AS TOTAL_SALES
FROM SALES
WHERE TO_CHAR(SALE_DATE, 'MM-YYYY') = '12-2023';


-- 4. Determine how many stores have never had a warranty claim filed.
SELECT COUNT(*)
FROM STORES
WHERE STORE_ID NOT IN (
SELECT DISTINCT STORE_ID
FROM SALES AS S
RIGHT JOIN WARRANTY AS W ON S.SALE_ID = W.SALE_ID
);

-- 5. Calculate the percentage of warranty claims marked as "Completed".

SELECT (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM WARRANTY))::NUMERIC
FROM WARRANTY
WHERE REPAIR_STATUS = 'Completed';

-- 6. Identify which store had the highest total units sold in 2023.
SELECT ST.STORE_ID, ST.STORE_NAME, SUM(S.QUANTITY) AS TOTAL_UNITS_SOLD
FROM STORES AS ST
JOIN SALES AS S ON ST.STORE_ID = S.STORE_ID
WHERE EXTRACT(YEAR FROM S.SALE_DATE) = 2023
GROUP BY ST.STORE_ID, ST.STORE_NAME
ORDER BY TOTAL_UNITS_SOLD DESC
LIMIT 1;

-- 7. Count the number of unique products sold in the 2023.
SELECT DISTINCT S.PRODUCT_ID, P.PRODUCT_NAME
FROM SALES AS S
JOIN PRODUCTS AS P ON P.PRODUCT_ID = S.PRODUCT_ID
WHERE EXTRACT(YEAR FROM SALE_DATE) = 2023;

-- 8. Find the average price of products in each category.
SELECT
	P.CATEGORY_ID,
	C.CATEGORY_NAME,
	AVG(P.PRICE) AS AVG_PRICE
FROM
	PRODUCTS AS P
	JOIN CATEGORY AS C ON P.CATEGORY_ID = C.CATEGORY_ID
GROUP BY
	P.CATEGORY_ID,
	C.CATEGORY_NAME
ORDER BY
	AVG_PRICE DESC;

--9. How many warranty claims were filed in 2024?

SELECT COUNT(*) AS TOTAL_CLAIMS
FROM WARRANTY
WHERE EXTRACT(YEAR FROM CLAIM_DATE) = 2024;

--10. For each store, identify the best-selling day based on highest quantity sold.

SELECT *
FROM (
SELECT STORE_ID,
TO_CHAR(SALE_DATE, 'Day') AS DAY_NAME,
SUM(QUANTITY) AS TOTAL_UNIT_SOLD,
RANK() OVER (PARTITION BY STORE_ID ORDER BY SUM(QUANTITY) DESC) AS RANK
FROM SALES
GROUP BY STORE_ID, DAY_NAME
) AS T1
WHERE RANK = 1;

-- 11. Identify the least selling product in each country based on total units sold.

WITH PRODUCT_RANK AS (
SELECT ST.COUNTRY, P.PRODUCT_NAME, SUM(S.QUANTITY) AS TOTAL_QTY_SOLD,
RANK() OVER (PARTITION BY ST.COUNTRY ORDER BY SUM(S.QUANTITY)) AS RANK
FROM SALES AS S
JOIN STORES AS ST ON S.STORE_ID = ST.STORE_ID
JOIN PRODUCTS AS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY 1,2
)
SELECT * FROM PRODUCT_RANK WHERE RANK = 1;


-- 12. Calculate how many warranty claims were filed within 180 days of a product sale.
SELECT
	COUNT(*)
FROM
	SALES AS S
	JOIN WARRANTY AS W ON S.SALE_ID = W.SALE_ID
WHERE
	W.CLAIM_DATE - S.SALE_DATE <= 180;

-- 13. Find sales info where warranty claims are filed within 180 days of a product sale.

SELECT * FROM
	SALES AS S
	JOIN WARRANTY AS W ON S.SALE_ID = W.SALE_ID
WHERE
	W.CLAIM_DATE - S.SALE_DATE <= 180;

-- 14. List the months in the last three years where sales exceeded 5,000 units in the USA.

SELECT TO_CHAR(SALE_DATE, 'MM-YYYY') AS MONTH,
SUM(S.QUANTITY) AS TOTAL_UNIT_SOLD
FROM SALES AS S
JOIN STORES AS ST ON S.STORE_ID = ST.STORE_ID
WHERE ST.COUNTRY = 'United States'
AND S.SALE_DATE >= CURRENT_DATE - INTERVAL '3 year'
GROUP BY MONTH
HAVING SUM(S.QUANTITY) > 5000;
	
-- 15. Identify the product category with the most warranty claims filed in year 2024.
	
SELECT CATEGORY_NAME, COUNT(W.CLAIM_ID) AS TOTAL_CLAIM
FROM WARRANTY W
JOIN SALES S ON W.SALE_ID = S.SALE_ID
JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
JOIN CATEGORY C ON C.CATEGORY_ID = P.CATEGORY_ID
WHERE EXTRACT(YEAR FROM W.CLAIM_DATE) = 2024
GROUP BY CATEGORY_NAME
ORDER BY TOTAL_CLAIM DESC;

--16. Determine the percentage chance of receiving warranty claims after each purchase for each country.

SELECT COUNTRY, TOTAL_UNIT_SOLD, TOTAL_CLAIM,
COALESCE(TOTAL_CLAIM::NUMERIC / TOTAL_UNIT_SOLD::NUMERIC * 100, 0) AS RISK
FROM (
SELECT ST.COUNTRY, SUM(S.QUANTITY) AS TOTAL_UNIT_SOLD, COUNT(W.CLAIM_ID) AS TOTAL_CLAIM
FROM SALES AS S
JOIN STORES AS ST ON S.STORE_ID = ST.STORE_ID
LEFT JOIN WARRANTY AS W ON W.SALE_ID = S.SALE_ID
GROUP BY COUNTRY
) T1
ORDER BY RISK DESC;

-- Q.17 Analyze the year-by-year growth ratio for each store each store and their yearly sale 

WITH YEARLY_SALES AS (
SELECT S.STORE_ID, ST.STORE_NAME,
EXTRACT(YEAR FROM SALE_DATE) AS YEAR,
SUM(S.QUANTITY * P.PRICE) AS TOTAL_SALE
FROM SALES AS S
JOIN PRODUCTS AS P ON S.PRODUCT_ID = P.PRODUCT_ID
JOIN STORES AS ST ON ST.STORE_ID = S.STORE_ID
GROUP BY S.STORE_ID, ST.STORE_NAME, YEAR
),
GROWTH_RATE AS (
SELECT STORE_NAME, YEAR,
LAG(TOTAL_SALE,1) OVER (PARTITION BY STORE_NAME ORDER BY YEAR) AS LAST_YEAR_SALE,
TOTAL_SALE AS CURRENT_YEAR_SALE
FROM YEARLY_SALES
)
SELECT STORE_NAME, YEAR, LAST_YEAR_SALE, CURRENT_YEAR_SALE,
ROUND((CURRENT_YEAR_SALE - LAST_YEAR_SALE)::NUMERIC / LAST_YEAR_SALE::NUMERIC * 100, 3) AS GROWTH_RATE
FROM GROWTH_RATE
WHERE LAST_YEAR_SALE IS NOT NULL
AND YEAR <> EXTRACT(YEAR FROM CURRENT_DATE);

-- Q.18 Calculate the correlation between product price and warranty claims for products sold in the last five years, segmented by price range.

SELECT
	CASE
		WHEN P.PRICE < 500 THEN 'Less Expensive Product'
		WHEN P.PRICE BETWEEN 500 AND 1000  THEN 'Mid Range Product'
		WHEN P.PRICE BETWEEN 1000 AND 1500  THEN ' Expensive Product'
		ELSE ' Very Expensive Product'
	END AS PRICE_SEGMENT,
	COUNT(W.CLAIM_ID) AS TOTAL_CLAIM
FROM
	WARRANTY AS W
	LEFT JOIN SALES AS S ON W.SALE_ID = S.SALE_ID
	JOIN PRODUCTS AS P ON P.PRODUCT_ID = S.PRODUCT_ID
WHERE
	CLAIM_DATE >= CURRENT_DATE - INTERVAL '5 year'
GROUP BY
	PRICE_SEGMENT;

-- Q.19 Write a query to calculate the monthly running total of sales for each store over the past four years and compare trends during this period.

WITH MONTHLY_SALES AS (
SELECT STORE_ID,
EXTRACT(YEAR FROM SALE_DATE) AS YEAR,
EXTRACT(MONTH FROM SALE_DATE) AS MONTH,
SUM(P.PRICE * S.QUANTITY) AS TOTAL_REVENUE
FROM SALES AS S
JOIN PRODUCTS AS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY STORE_ID, YEAR, MONTH
)
SELECT STORE_ID, MONTH, YEAR, TOTAL_REVENUE,
SUM(TOTAL_REVENUE) OVER (PARTITION BY STORE_ID ORDER BY YEAR, MONTH) AS RUNNING_TOTAL
FROM MONTHLY_SALES;

--Q.20 Analyze product sales trends over time, segmented into key periods: from launch to 6 months, 6-12 months, 12-18 months, and beyond 18 months.
SELECT
	P.PRODUCT_NAME,
	CASE
		WHEN S.SALE_DATE BETWEEN P.LAUNCH_DATE AND P.LAUNCH_DATE  + INTERVAL '6 month' THEN '0-6 month'
		WHEN S.SALE_DATE BETWEEN P.LAUNCH_DATE + INTERVAL '6 month' AND P.LAUNCH_DATE  + INTERVAL '12 month' THEN '6-12'
		WHEN S.SALE_DATE BETWEEN P.LAUNCH_DATE + INTERVAL '12 month' AND P.LAUNCH_DATE  + INTERVAL '18 month' THEN '6-12'
		ELSE '18+'
	END AS PLC,
	SUM(S.QUANTITY) AS TOTAL_QTY_SALE
FROM
	SALES AS S
	JOIN PRODUCTS AS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
	P.PRODUCT_NAME,
	PLC
ORDER BY
	P.PRODUCT_NAME,
	TOTAL_QTY_SALE DESC;